GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/682d7e39808172355bda8a93

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "John Doe",
  "number": "123456789"
}